-- 1.3 DBMS_XPLAN.DISPLAY_CURSOR 사용 권한 부여

GRANT SELECT ON V_$SQL TO DEV;
GRANT SELECT ON V_$SESSION TO DEV;
GRANT SELECT ON V_$SQL_PLAN TO DEV;
GRANT SELECT ON V_$SQL_PLAN_STATISTICS_ALL TO DEV;

ALTER SESSION SET STATISTICS_LEVEL = ALL;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL,NULL,'ADVANCED ALLSTATS LAST'));
DBMS_XPLAN.DISPLAY_CURSOR(SQL_ID, CHILD NUMBER, 'ADVANCED ALLSTATS LAST')

SELECT /*+ gather_plan_statistics */
        *
FROM    (
            SELECT * 
            FROM    EMP
            WHERE   DEPTNO = 30
            ORDER BY ENAME
        )
WHERE   ROWNUM <= 3;